### ISSUE TITLE
Huawei P8 Lite Alice

### ISSUE THREAD

**Issue by Ozwald1** [Halium/projectmanagement#201] opened 2020-06-27 16:03 UTC
Tree: 

- [x] Create manifest 
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

**Comment by ijiki16** [comment] 2020-06-27 16:46
Please look at this, if the issue is the same close this one. https://github.com/Halium/projectmanagement/issues/78#issuecomment-650548327

**Closed as completed** 2020-06-27 21:47 UTC
