### ISSUE TITLE
lge Nexus 5x 

### ISSUE THREAD

**Issue by hagdervriese** [Halium/projectmanagement#161] opened 2019-11-01 19:59 UTC
Tree: 

- [x] Create manifest 
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

**Comment by amichuda** [comment] 2019-11-16 04:12
Hi I'm working on porting the 5x as well, how has it been going for you? Has it worked?

**Comment by hagdervriese** [comment] 2019-11-16 07:27
hi there, it was a bit dissapointing, i couldnt get the gui working. i think the rootfs is not optimized right for the arm64 architecture. because of that, an the fact that i am not experienced in porting, i gave up trying it. I got everything halium related build, but after after installing rootfs and starting it, i got stucked

Von meinem iPhone gesendet

**Comment by amichuda** [comment] 2019-11-16 21:01
Were you able to get past the boot screen? I installed it, but I'm getting a very fast bootloop, like the Google logo is there for less than a second and it reboots...

**Comment by hagdervriese** [comment] 2019-11-17 08:01
no, it stays at the boot screen and was able to connect via ssh. but that was it, nothing more. 

Von meinem iPhone gesendet

**Comment by hagdervriese** [comment] 2019-11-17 08:04
i could look, if i find the mk.config and the defconfig and sent it to you

Von meinem iPhone gesendet

**Comment by 4soobs** [comment] 2019-11-17 09:25
> Were you able to get past the boot screen? I installed it, but I'm getting a very fast bootloop, like the Google logo is there for less than a second and it reboots...

Might be a kernel panic. What does last_kmsg say?

**Comment by amichuda** [comment] 2019-11-17 09:33
> Might be a kernel panic. What does last_kmsg say?

How would I access that? As it stands now I have TWRP recovery on it... Can I read it through the terminal there?

**Comment by amichuda** [comment] 2019-11-17 09:34
> i could look, if i find the mk.config and the defconfig and sent it to you

That would be great. I tried to follow the meet checker and change my kernel config as per those recommendations, but I'm not sure I did it right...

**Comment by 4soobs** [comment] 2019-11-17 09:35
> > Might be a kernel panic. What does last_kmsg say?
> 
> How would I access that? As it stands now I have TWRP recovery on it... Can I read it through the terminal there?

Yep! Wait until the kernel reboots, then boot into TWRP, plug your phone into your PC and fire up the terminal. Then type `adb devices` and make sure there is a device listed. After you made sure it's listed, type `adb pull /proc/last_kmsg/ ~/` The last_kmsg will be pulled into your home folder.

**Comment by amichuda** [comment] 2019-11-17 09:43
Hmm so it doesn't seem like I have `/proc/last_kmsg`, only `/proc/kmsg`... Could that help?

**Comment by 4soobs** [comment] 2019-11-17 09:44
> Hmm so it doesn't seem like I have `/proc/last_kmsg`, only `/proc/kmsg`... Could that help?

Not sure, but paste it to pastebin, I will take a look.

**Comment by amichuda** [comment] 2019-11-17 09:53
Okay here it is:

https://pastebin.com/KiL6narD

**Comment by amichuda** [comment] 2019-11-17 09:58
Is it something here:

```
<6>[    1.114575] mdss_mdp_parse_dt_prop_len: prop qcom,mdss-clk-levels : doesn't exist in device tree
<6>[    1.114729] mdss_mdp_parse_dt_prop_len: prop qcom,mdss-ad-off : doesn't exist in device tree
<3>[    1.115147] mdss_mdp_irq_clk_register: unable to get clk: lut_clk
<3>[    1.115806] getpath: Cannot locate src dev 36
<3>[    1.115881] register_client_adhoc:Failed to find path.src 36 dest 627
<4>[    1.116088] mdss_mdp_bus_scale_register: reg_bus_client register failed
<6>[    1.134299] xlog_status: enable:0, panic:1, dump:2
```

**Comment by amichuda** [comment] 2019-11-17 10:16
Also, based on:

https://docs.halium.org/en/latest/porting/debug-build/dmesg.html

it would seem that I can also look in `/sys/fs/pstore/console-ramoops`, but the `pstore` folder is empty, it seems...

**Comment by amichuda** [comment] 2019-11-17 10:24
Could this be an issue:

```
<3>[    0.003056] /cpus/cpu@0: Missing clock-frequency property
<3>[    0.003138] /cpus/cpu@1: Missing clock-frequency property
<3>[    0.003152] /cpus/cpu@2: Missing clock-frequency property
<3>[    0.003167] /cpus/cpu@3: Missing clock-frequency property
<3>[    0.003182] /cpus/cpu@4: Missing clock-frequency property
<3>[    0.003199] /cpus/cpu@5: Missing clock-frequency property
```

**Comment by doniks** [comment] 2019-11-19 09:19
Is this a duplicate of https://github.com/Halium/projectmanagement/issues/17 ?

**Comment by amichuda** [comment] 2019-11-19 17:30
It's definitely the same phone, but it seems like that user was able to go further then I was. Is there a place I can go to get their kernel config? That's the only thing that could be different from my case and their case right?

**Comment by doniks** [comment] 2019-11-19 20:39
here https://github.com/Halium/halium-devices/blob/halium-7.1/manifests/lge_bullhead.xml I assume. and @bhush9  and @UniversalSuperBox are hanging around in the irc/telegram channel: http://docs.halium.org/en/latest/porting/first-steps.html#getting-help

**Comment by doniks** [comment] 2020-01-04 17:20
duplicate of #17

**Closed as completed by doniks** 2020-01-04 17:20 UTC
